version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "9090:80"
    volumes:
      - /mnt/project:/usr/share/nginx/html

# not: k3s kullanıldığı takdirde bu dosyaya ihtiyaç yoktur.
# k3s klasöründe, deployment.yaml içindeki template kısmında
# bu yml dosyasındaki aynı işlemler aynen yapılmaktadır.
