pipeline {
    agent any

    stages {
        stage('clone') {
            steps {
                git branch: '$branch_name', url: 'https://github.com/norcholly/devops-lab.git'
                echo ' ===== CLONE COMPLETED ===== '
            }
        }
        
        stage('build') {
            steps {
                dir('mikro-servis-projesi') {
                    sh 'docker compose up -d --build'
                    echo ' ===== BUILD COMPLETED ====='
                }
            }
        }
        
        stage('notification') {
            steps {
                emailext body: "The build numbered ${env.BUILD_NUMBER} on the ${env.GIT_BRANCH} branch named ${env.JOB_NAME} has been completed.", 
                 subject: "Build ${env.BUILD_NUMBER} Completed", 
                 to: "alirfandogan@gmail.com"
            }
        }
    }
}
